// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kspnaakitiarthduloya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzcG5hYWtpdGlhcnRoZHVsb3lhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzUwNDIsImV4cCI6MjA2MDk1MTA0Mn0.bcGmlgDa17tQUIwdKqqEV-w9zZUk2fMK93YEoIu4kj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);